#!/usr/bin/python3
## That's just there so vim's filetype editing

import os
import platform
import random

xontrib load bashisms
xontrib load vox

def _hostname_colour():
    r = random.Random()
    r.seed(platform.node())

    colour_index = r.randint(0, 6)
    colours = ["RED", "GREEN", "YELLOW", "BLUE", "PURPLE", "CYAN", "WHITE"]

    colour = colours[colour_index]

    is_bold = r.random() < 0.5
    if is_bold:
        colour = "BOLD_" + colour

    return colour

# Gdb won't run properly unless it has the SHELL var set to /bin/bash
# Also, -q because it's noisy.
aliases['gdb'] = 'env SHELL=/bin/bash gdb -q'

$PROMPT = '{env_name:{} }{NO_COLOR}{user}@{' + _hostname_colour() + '}{hostname}{NO_COLOR}:{BOLD_BLUE}{cwd}{NO_COLOR}{gitstatus:[{}]}{NO_COLOR}{prompt_end} '
